server:
  port: 8082
spring:
  rabbitmq:
    request:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchenge:
      producer: ex.producer.desafio
    routing-key:
      producer: rk.producer.desafio
    deadletter:
      producer: dl.producer.desafio